### ISSUE TITLE
Undelared dependency urllib3

### ISSUE THREAD

**Issue by luandy64** [square/square-python-sdk#33]
I am doing some spiking for a project and was attempting to run the example code in the README.

```
Traceback (most recent call last):
  File "sync.py", line 1, in <module>
    from square.client import Client
  File "/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/square/client.py", line 4, in <module>
    from square.configuration import Configuration
  File "/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/square/configuration.py", line 4, in <module>
    from square.http.requests_client import RequestsClient
  File "/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/square/http/requests_client.py", line 6, in <module>
    from urllib3.util.retry import Retry
ImportError: No module named 'urllib3'
```

`square` seems to be happy if `urllib3 1.25.9` is installed. Is this a good version to use or should something else be pinned in `square-python-sdk/setup.py`?

**Comment by jessdelacruzsantos** [comment]
Hello @ luandy64. It turns out that `urllib3` is a dependency of `requests` which our SDK depends on. Here is their[ setup.py](https://github.com/psf/requests/blob/master/setup.py#L47). It seems you are encountering an issue installing dependencies.
