### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

### ISSUE THREAD

**Issue by babishdesai** [square/square-python-sdk#66]
i keep getting below error  on raspberry pi with python 2.7.16

Traceback (most recent call last):
  File "orders.py", line 10, in <module>
    environment='sandbox',
  File "/home/pi/orders/square/client.py", line 203, in __init__
    additional_headers=additional_headers)
  File "/home/pi/orders/square/configuration.py", line 96, in __init__
    self._http_client = self.create_http_client()
  File "/home/pi/orders/square/configuration.py", line 127, in create_http_client
    retry_methods=self.retry_methods)
  File "/home/pi/orders/square/http/requests_client.py", line 40, in __init__
    status_forcelist=retry_statuses, allowed_methods=retry_methods)
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

**Comment by bobby-alter** [comment]
I'm started getting this error too, on Mac OS with Python 3.8.

**Comment by kwamena98** [comment]
Me too

**Comment by kwamena98** [comment]
Can you guys help out

**Comment by kwamena98** [comment]
> I'm started getting this error too, on Mac OS with Python 3.8.

Did you get the solution?

**Comment by isaac-rego** [comment]
you can solve this issue by upgrading urllib3 to 1.26.x

**Comment by kwamena98** [comment]
why don't you guys use Curl in python

**Comment by Murithijoshua** [comment]
Was this issue solved.Am getting this error as well `Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/usr/local/lib/python3.7/site-packages/square/client.py", line 248, in __init__
    user_agent_detail=user_agent_detail)
  File "/usr/local/lib/python3.7/site-packages/square/configuration.py", line 68, in __init__
    super().set_http_client(self.create_http_client())
  File "/usr/local/lib/python3.7/site-packages/square/configuration.py", line 109, in create_http_client
    response_factory=super().http_response_factory
  File "/usr/local/lib/python3.7/site-packages/apimatic_requests_client_adapter/requests_client.py", line 42, in __init__
    retry_methods, verify)
  File "/usr/local/lib/python3.7/site-packages/apimatic_requests_client_adapter/requests_client.py", line 70, in create_default_http_client
    status_forcelist=retry_statuses, allowed_methods=retry_methods)
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
`

**Comment by zenmasterjobo** [comment]
Hi @Murithijoshua

What version of the SDK are you using? Can you share the code you are using to invoke the SDK that is causing this error?

We also suggest posting questions to our [Developer Forums](https://developer.squareup.com/forums) as it is more widely monitored, and has active activity from Square Employees and developers in the Community. 

Cheers!

**Comment by Murithijoshua** [comment]
@zenmasterjobo I found the solution, I just used python requests instead.Thanks

**Comment by zenmasterjobo** [comment]
Closing this issue, but if anyone runs into this problem again, please feel free to re-open! 

Thanks :)
